package:
  name: scardock-util
  version: 0.1.0

source:
  path: .

build:
  number: 0
  skip: True  # [not linux64]

requirements:
  host:
    - python =3.10
    - conda-forge::pyyaml
    - pip
    - setuptools
    - git
  run:
    - python =3.10
    - conda-forge::pdbfixer
    - conda-forge::openmm
    - bioconda::mgltools
    - conda-forge::spyrmsd
    - conda-forge::pandas
    - conda-forge::openbabel
    - conda-forge::rdkit
    - conda-forge::pymol-open-source 2.5.0 py310h292d129_6
    - conda-forge::loguru
    - conda-forge::vina 1.2.3 py310he924329_2
    - conda-forge::ipython
    - conda-forge::biopython
    - conda-forge::prody # meeko dependency

test:
  commands:
    - scardock --help

about:
  home: https://github.com/SenLiu-Lab/SCARdock-util.git
  license: MIT
  license_file: LICENSE
  summary: 'A Comprehensive Toolkit for SCARdock Covalent Docking and Molecular Modeling'
  description: |
    SCARdock-util provides end-to-end automated covalent docking workflows,
    lossless PDBQT-to-MOL2 bond order restoration, pocket detection with Fpocket
    and DeepPocket, and symmetry-corrected RMSD calculation for AutoDock Vina.
  dev_url: https://github.com/SenLiu-Lab/SCARdock-util.git
  doc_url: https://github.com/SenLiu-Lab/SCARdock-util.git
  doc_source_url: https://github.com/SenLiu-Lab/SCARdock-util.git
